# Generated by Django 5.1.5 on 2025-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
