# Generated by Django 5.1.5 on 2025-02-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_last_login_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="scheduled_deletion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
