# Generated by Django 5.1.5 on 2025-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_scheduled_deletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lockout_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
